Style kit and UI
rvanderwesthuizen/MrMovieInfo pull request #29
Opened 2021-11-18 08:40 UTC by rvanderwesthuizen

Created extension of UIColor and UIFont to hold the colors and fonts used in the app

Added a class that holds the fonts and colors that are assigned in the app

Then assigned the colors programmatically to all elements

2021-11-18 17:12 UTC, bgouws approved these changes

2021-11-18 17:12 UTC, bgouws commented on Mr Movie Info/Mr Movie Info/Styling/UIColor+UIFontExtentions.swift
> +        UIColor(named: "PrimaryColor") ?? .white
Nice 😄

2021-11-18 19:03 UTC, justinewright requested changes

2021-11-18 19:03 UTC, justinewright commented on Mr Movie Info/Mr Movie Info/Feature-Main/ViewController/MainTableViewController.swift
> +    private func preformStyling() {
spelling, but maybe change to "styling" to keep it consistent with the rest of your classes

2021-11-19 05:09 UTC, justinewright approved these changes

2021-11-19 05:16 UTC, merged